version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: jojobank
      MYSQL_USER: jojo
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
